const periodictabledata =
[
    {
        name: "Hidrojen",
        atomicnumber: 1,
        symbol: "H",
        category: "Reaktif ametal",
        atomicweight: "1.008",
        atomicweightfull: "[1.00784, 1.00811]",
        occurrence: "Gaz",
        stateofmatter: "İlkel element",
        group: 1,
        period: 1,
        block: "s",
        tablerow18col: 1,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Helyum",
        atomicnumber: 2,
        symbol: "He",
        category: "Soygaz",
        atomicweight: "4.0026",
        atomicweightfull: "4.002602(2)",
        occurrence: "Gaz",
        stateofmatter: "İlkel element",
        group: 18,
        period: 1,
        block: "s",
        tablerow18col: 1,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Lityum",
        atomicnumber: 3,
        symbol: "Li",
        category: "Alkali metal",
        atomicweight: "6.94",
        atomicweightfull: "[6.938, 6.997]",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 1,
        period: 2,
        block: "s",
        tablerow18col: 2,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Berilyum",
        atomicnumber: 4,
        symbol: "Be",
        category: "Toprak alkali metal",
        atomicweight: "9.0122",
        atomicweightfull: "9.0121831(5)",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 2,
        period: 2,
        block: "s",
        tablerow18col: 2,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Bor",
        atomicnumber: 5,
        symbol: "B",
        category: "Yarı metal",
        atomicweight: "10.81",
        atomicweightfull: "[10.806, 10.821]",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 13,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Karbon",
        atomicnumber: 6,
        symbol: "C",
        category: "Reaktif ametal",
        atomicweight: "12.011",
        atomicweightfull: "[12.0096, 12.0116]",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 14,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Nitrojen",
        atomicnumber: 7,
        symbol: "N",
        category: "Reaktif ametal",
        atomicweight: "14.007",
        atomicweightfull: "[14.00643, 14.00728]",
        occurrence: "Gaz",
        stateofmatter: "İlkel element",
        group: 15,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Oksijen",
        atomicnumber: 8,
        symbol: "O",
        category: "Reaktif ametal",
        atomicweight: "15.999",
        atomicweightfull: "[15.99903, 15.99977]",
        occurrence: "Gaz",
        stateofmatter: "İlkel element",
        group: 16,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Flor",
        atomicnumber: 9,
        symbol: "F",
        category: "Reaktif ametal",
        atomicweight: "18.998",
        atomicweightfull: "18.998403163(6)",
        occurrence: "Gaz",
        stateofmatter: "İlkel element",
        group: 17,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Neon",
        atomicnumber: 10,
        symbol: "Ne",
        category: "Soygaz",
        atomicweight: "20.18",
        atomicweightfull: "20.1797(6)",
        occurrence: "Gaz",
        stateofmatter: "İlkel element",
        group: 18,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Sodyum",
        atomicnumber: 11,
        symbol: "Na",
        category: "Alkali metal",
        atomicweight: "22.99",
        atomicweightfull: "22.98976928(2) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 1,
        period: 3,
        block: "s",
        tablerow18col: 3,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Magnezyum",
        atomicnumber: 12,
        symbol: "Mg",
        category: "Toprak alkali metal",
        atomicweight: "24.305",
        atomicweightfull: "[24.304, 24.307] ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 2,
        period: 3,
        block: "s",
        tablerow18col: 3,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Aliminyum",
        atomicnumber: 13,
        symbol: "Al",
        category: "Zayıf metal",
        atomicweight: "26.982",
        atomicweightfull: "26.9815384(3) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 13,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Silikon",
        atomicnumber: 14,
        symbol: "Si",
        category: "Yarı metal",
        atomicweight: "28.085",
        atomicweightfull: "[28.084, 28.086] ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 14,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Fosfor",
        atomicnumber: 15,
        symbol: "P",
        category: "Reaktif ametal",
        atomicweight: "30.974",
        atomicweightfull: "30.973761998(5) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 15,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Kükürt",
        atomicnumber: 16,
        symbol: "S",
        category: "Reaktif ametal",
        atomicweight: "32.06",
        atomicweightfull: "[32.059, 32.076] ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 16,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Klor",
        atomicnumber: 17,
        symbol: "Cl",
        category: "Reaktif ametal",
        atomicweight: "35.45",
        atomicweightfull: "[35.446, 35.457] ",
        occurrence: "Gaz",
        stateofmatter: "İlkel element",
        group: 17,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Argon",
        atomicnumber: 18,
        symbol: "Ar",
        category: "Soygaz",
        atomicweight: "39.95",
        atomicweightfull: "[39.792, 39.963] ",
        occurrence: "Gaz",
        stateofmatter: "İlkel element",
        group: 18,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Potasyum",
        atomicnumber: 19,
        symbol: "K",
        category: "Alkali metal",
        atomicweight: "39.098",
        atomicweightfull: "39.0983(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 1,
        period: 4,
        block: "s",
        tablerow18col: 4,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Kalsiyum",
        atomicnumber: 20,
        symbol: "Ca",
        category: "Toprak alkali metal",
        atomicweight: "40.078",
        atomicweightfull: "40.078(4) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 2,
        period: 4,
        block: "s",
        tablerow18col: 4,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Skandiyum",
        atomicnumber: 21,
        symbol: "Sc",
        category: "Geçiş metali",
        atomicweight: "44.956",
        atomicweightfull: "44.955908(5) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 3,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 3,
        visible: true
    },
    {
        name: "Titanyum",
        atomicnumber: 22,
        symbol: "Ti",
        category: "Geçiş metali",
        atomicweight: "47.867",
        atomicweightfull: "47.867(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 4,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Vanadyum",
        atomicnumber: 23,
        symbol: "V",
        category: "Geçiş metali",
        atomicweight: "50.942",
        atomicweightfull: "50.9415(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 5,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Krom",
        atomicnumber: 24,
        symbol: "Cr",
        category: "Geçiş metali",
        atomicweight: "51.996",
        atomicweightfull: "51.9961(6) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 6,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Mangan",
        atomicnumber: 25,
        symbol: "Mn",
        category: "Geçiş metali",
        atomicweight: "54.938",
        atomicweightfull: "54.938043(2) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 7,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Demir",
        atomicnumber: 26,
        symbol: "Fe",
        category: "Geçiş metali",
        atomicweight: "55.845",
        atomicweightfull: "55.845(2) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 8,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Kobalt",
        atomicnumber: 27,
        symbol: "Co",
        category: "Geçiş metali",
        atomicweight: "58.933",
        atomicweightfull: "58.933194(3) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 9,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Nikel",
        atomicnumber: 28,
        symbol: "Ni",
        category: "Geçiş metali",
        atomicweight: "58.693",
        atomicweightfull: "58.6934(4) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 10,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Bakır",
        atomicnumber: 29,
        symbol: "Cu",
        category: "Geçiş metali",
        atomicweight: "63.546",
        atomicweightfull: "63.546(3) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 11,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Çinko",
        atomicnumber: 30,
        symbol: "Zn",
        category: "Zayıf metal",
        atomicweight: "65.38",
        atomicweightfull: "65.38(2) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 12,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Galyum",
        atomicnumber: 31,
        symbol: "Ga",
        category: "Zayıf metal",
        atomicweight: "69.723",
        atomicweightfull: "69.723(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 13,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Germanyum",
        atomicnumber: 32,
        symbol: "Ge",
        category: "Yarı metal",
        atomicweight: "72.63",
        atomicweightfull: "72.630(8) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 14,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Arsenik",
        atomicnumber: 33,
        symbol: "As",
        category: "Yarı metal",
        atomicweight: "74.922",
        atomicweightfull: "74.921595(6) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 15,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Selenyum",
        atomicnumber: 34,
        symbol: "Se",
        category: "Reaktif ametal",
        atomicweight: "78.971",
        atomicweightfull: "78.971(8) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 16,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Brom",
        atomicnumber: 35,
        symbol: "Br",
        category: "Reaktif ametal",
        atomicweight: "79.904",
        atomicweightfull: "[79.901, 79.907] ",
        occurrence: "Sıvı",
        stateofmatter: "İlkel element",
        group: 17,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Kripton",
        atomicnumber: 36,
        symbol: "Kr",
        category: "Soygaz",
        atomicweight: "83.798",
        atomicweightfull: "83.798(2) ",
        occurrence: "Gaz",
        stateofmatter: "İlkel element",
        group: 18,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Rubidyum",
        atomicnumber: 37,
        symbol: "Rb",
        category: "Alkali metal",
        atomicweight: "85.468",
        atomicweightfull: "85.4678(3) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 1,
        period: 5,
        block: "s",
        tablerow18col: 5,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Stronsiyum",
        atomicnumber: 38,
        symbol: "Sr",
        category: "Toprak alkali metal",
        atomicweight: "87.62",
        atomicweightfull: "87.62(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 2,
        period: 5,
        block: "s",
        tablerow18col: 5,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "İtriyum",
        atomicnumber: 39,
        symbol: "Y",
        category: "Geçiş metali",
        atomicweight: "88.906",
        atomicweightfull: "88.90584(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 3,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 3,
        visible: true
    },
    {
        name: "Zirkonyum",
        atomicnumber: 40,
        symbol: "Zr",
        category: "Geçiş metali",
        atomicweight: "91.224",
        atomicweightfull: "91.224(2) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 4,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Niyobyum",
        atomicnumber: 41,
        symbol: "Nb",
        category: "Geçiş metali",
        atomicweight: "92.906",
        atomicweightfull: "92.90637(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 5,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Molibden",
        atomicnumber: 42,
        symbol: "Mo",
        category: "Geçiş metali",
        atomicweight: "95.95",
        atomicweightfull: "95.95(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 6,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Teknesyum",
        atomicnumber: 43,
        symbol: "Tc",
        category: "Geçiş metali",
        atomicweight: "[97]",
        atomicweightfull: "-",
        occurrence: "Katı",
        stateofmatter: "Radyoaktif",
        group: 7,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Rutenyum",
        atomicnumber: 44,
        symbol: "Ru",
        category: "Geçiş metali",
        atomicweight: "101.07",
        atomicweightfull: "101.07(2) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 8,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Rodyum",
        atomicnumber: 45,
        symbol: "Rh",
        category: "Geçiş metali",
        atomicweight: "102.91",
        atomicweightfull: "102.90549(2) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 9,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Paladyum",
        atomicnumber: 46,
        symbol: "Pd",
        category: "Geçiş metali",
        atomicweight: "106.42",
        atomicweightfull: "106.42(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 10,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Gümüş",
        atomicnumber: 47,
        symbol: "Ag",
        category: "Geçiş metali",
        atomicweight: "107.87",
        atomicweightfull: "107.8682(2) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 11,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Kadmiyum",
        atomicnumber: 48,
        symbol: "Cd",
        category: "Zayıf metal",
        atomicweight: "112.41",
        atomicweightfull: "112.414(4) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 12,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "İndiyum",
        atomicnumber: 49,
        symbol: "In",
        category: "Zayıf metal",
        atomicweight: "114.82",
        atomicweightfull: "114.818(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 13,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Kalay",
        atomicnumber: 50,
        symbol: "Sn",
        category: "Zayıf metal",
        atomicweight: "118.71",
        atomicweightfull: "118.710(7) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 14,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Antimon",
        atomicnumber: 51,
        symbol: "Sb",
        category: "Yarı metal",
        atomicweight: "121.76",
        atomicweightfull: "121.760(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 15,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Tellür",
        atomicnumber: 52,
        symbol: "Te",
        category: "Yarı metal",
        atomicweight: "127.6",
        atomicweightfull: "127.60(3) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 16,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "İyot",
        atomicnumber: 53,
        symbol: "I",
        category: "Reaktif ametal",
        atomicweight: "126.9",
        atomicweightfull: "126.90447(3) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 17,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Ksenon",
        atomicnumber: 54,
        symbol: "Xe",
        category: "Soygaz",
        atomicweight: "131.29",
        atomicweightfull: "131.293(6) ",
        occurrence: "Gaz",
        stateofmatter: "İlkel element",
        group: 18,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Sezyum",
        atomicnumber: 55,
        symbol: "Cs",
        category: "Alkali metal",
        atomicweight: "132.91",
        atomicweightfull: "132.90545196(6) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 1,
        period: 6,
        block: "s",
        tablerow18col: 6,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Baryum",
        atomicnumber: 56,
        symbol: "Ba",
        category: "Toprak alkali metal",
        atomicweight: "137.33",
        atomicweightfull: "137.327(7) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 2,
        period: 6,
        block: "s",
        tablerow18col: 6,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Lantanyum",
        atomicnumber: 57,
        symbol: "La",
        category: "Lantanit",
        atomicweight: "138.91",
        atomicweightfull: "138.90547(7) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 3,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 3,
        visible: true
    },
    {
        name: "Seryum",
        atomicnumber: 58,
        symbol: "Ce",
        category: "Lantanit",
        atomicweight: "140.12",
        atomicweightfull: "140.116(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Praseodimyum",
        atomicnumber: 59,
        symbol: "Pr",
        category: "Lantanit",
        atomicweight: "140.91",
        atomicweightfull: "140.90766(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Neodimyum",
        atomicnumber: 60,
        symbol: "Nd",
        category: "Lantanit",
        atomicweight: "144.24",
        atomicweightfull: "144.242(3) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Prometyum",
        atomicnumber: 61,
        symbol: "Pm",
        category: "Lantanit",
        atomicweight: "[145]",
        atomicweightfull: "-",
        occurrence: "Katı",
        stateofmatter: "Radyoaktif",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Samaryum",
        atomicnumber: 62,
        symbol: "Sm",
        category: "Lantanit",
        atomicweight: "150.36",
        atomicweightfull: "150.36(2) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Evropiyum",
        atomicnumber: 63,
        symbol: "Eu",
        category: "Lantanit",
        atomicweight: "151.96",
        atomicweightfull: "151.964(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Gadolinyum",
        atomicnumber: 64,
        symbol: "Gd",
        category: "Lantanit",
        atomicweight: "157.25",
        atomicweightfull: "157.25(3) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Terbiyum",
        atomicnumber: 65,
        symbol: "Tb",
        category: "Lantanit",
        atomicweight: "158.93",
        atomicweightfull: "158.925354(8) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Disporsiyum",
        atomicnumber: 66,
        symbol: "Dy",
        category: "Lantanit",
        atomicweight: "162.5",
        atomicweightfull: "162.500(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Holmiyum",
        atomicnumber: 67,
        symbol: "Ho",
        category: "Lantanit",
        atomicweight: "164.93",
        atomicweightfull: "164.930328(7) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Erbiyum",
        atomicnumber: 68,
        symbol: "Er",
        category: "Lantanit",
        atomicweight: "167.26",
        atomicweightfull: "167.259(3) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Tülyum",
        atomicnumber: 69,
        symbol: "Tm",
        category: "Lantanit",
        atomicweight: "168.93",
        atomicweightfull: "168.934218(6) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "İterbiyum",
        atomicnumber: 70,
        symbol: "Yb",
        category: "Lantanit",
        atomicweight: "173.05",
        atomicweightfull: "173.045(10) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Lutenyum",
        atomicnumber: 71,
        symbol: "Lu",
        category: "Lantanit",
        atomicweight: "174.97",
        atomicweightfull: "174.9668(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 0,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 3,
        visible: true
    },
    {
        name: "Hafniyum",
        atomicnumber: 72,
        symbol: "Hf",
        category: "Geçiş metali",
        atomicweight: "178.49",
        atomicweightfull: "178.49(2) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 4,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Tantal",
        atomicnumber: 73,
        symbol: "Ta",
        category: "Geçiş metali",
        atomicweight: "180.95",
        atomicweightfull: "180.94788(2) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 5,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Tungsten",
        atomicnumber: 74,
        symbol: "W",
        category: "Geçiş metali",
        atomicweight: "183.84",
        atomicweightfull: "183.84(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 6,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Renyum",
        atomicnumber: 75,
        symbol: "Re",
        category: "Geçiş metali",
        atomicweight: "186.21",
        atomicweightfull: "186.207(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 7,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Osmiyum",
        atomicnumber: 76,
        symbol: "Os",
        category: "Geçiş metali",
        atomicweight: "190.23",
        atomicweightfull: "190.23(3) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 8,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "İridyum",
        atomicnumber: 77,
        symbol: "Ir",
        category: "Geçiş metali",
        atomicweight: "192.22",
        atomicweightfull: "192.217(2) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 9,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Platin",
        atomicnumber: 78,
        symbol: "Pt",
        category: "Geçiş metali",
        atomicweight: "195.08",
        atomicweightfull: "195.084(9) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 10,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Altın",
        atomicnumber: 79,
        symbol: "Au",
        category: "Geçiş metali",
        atomicweight: "196.97",
        atomicweightfull: "196.966570(4) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 11,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Cıva",
        atomicnumber: 80,
        symbol: "Hg",
        category: "Zayıf metal",
        atomicweight: "200.59",
        atomicweightfull: "200.592(3) ",
        occurrence: "Sıvı",
        stateofmatter: "İlkel element",
        group: 12,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Talyum",
        atomicnumber: 81,
        symbol: "Tl",
        category: "Zayıf metal",
        atomicweight: "204.38",
        atomicweightfull: "[204.382, 204.385] ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 13,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Kurşun",
        atomicnumber: 82,
        symbol: "Pb",
        category: "Zayıf metal",
        atomicweight: "207.2",
        atomicweightfull: "207.2(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 14,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Bizmut",
        atomicnumber: 83,
        symbol: "Bi",
        category: "Zayıf metal",
        atomicweight: "208.98",
        atomicweightfull: "208.98040(1) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 15,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Polonyum",
        atomicnumber: 84,
        symbol: "Po",
        category: "Zayıf metal",
        atomicweight: "[209]",
        atomicweightfull: "-",
        occurrence: "Katı",
        stateofmatter: "Radyoaktif",
        group: 16,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Astatin",
        atomicnumber: 85,
        symbol: "At",
        category: "Yarı metal",
        atomicweight: "[210]",
        atomicweightfull: "-",
        occurrence: "Katı",
        stateofmatter: "Radyoaktif",
        group: 17,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Radon",
        atomicnumber: 86,
        symbol: "Rn",
        category: "Soygaz",
        atomicweight: "[222]",
        atomicweightfull: "-",
        occurrence: "Gaz",
        stateofmatter: "Radyoaktif",
        group: 18,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Fransiyum",
        atomicnumber: 87,
        symbol: "Fr",
        category: "Alkali metal",
        atomicweight: "[223]",
        atomicweightfull: "-",
        occurrence: "Katı",
        stateofmatter: "Radyoaktif",
        group: 1,
        period: 7,
        block: "s",
        tablerow18col: 7,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Radyum",
        atomicnumber: 88,
        symbol: "Ra",
        category: "Toprak alkali metal",
        atomicweight: "[226]",
        atomicweightfull: "-",
        occurrence: "Katı",
        stateofmatter: "Radyoaktif",
        group: 2,
        period: 7,
        block: "s",
        tablerow18col: 7,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Aktinyum",
        atomicnumber: 89,
        symbol: "Ac",
        category: "Aktinit",
        atomicweight: "[227]",
        atomicweightfull: "-",
        occurrence: "Katı",
        stateofmatter: "Radyoaktif",
        group: 3,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 3,
        visible: true
    },
    {
        name: "Toryum",
        atomicnumber: 90,
        symbol: "Th",
        category: "Aktinit",
        atomicweight: "232.04",
        atomicweightfull: "232.0377(4) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Protaktinyum",
        atomicnumber: 91,
        symbol: "Pa",
        category: "Aktinit",
        atomicweight: "231.04",
        atomicweightfull: "231.03588(1) ",
        occurrence: "Katı",
        stateofmatter: "Radyoaktif",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Uranyum",
        atomicnumber: 92,
        symbol: "U",
        category: "Aktinit",
        atomicweight: "238.03",
        atomicweightfull: "238.02891(3) ",
        occurrence: "Katı",
        stateofmatter: "İlkel element",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Neptünyum",
        atomicnumber: 93,
        symbol: "Np",
        category: "Aktinit",
        atomicweight: "[237]",
        atomicweightfull: "-",
        occurrence: "Katı",
        stateofmatter: "Radyoaktif",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Plütonyum",
        atomicnumber: 94,
        symbol: "Pu",
        category: "Aktinit",
        atomicweight: "[244]",
        atomicweightfull: "-",
        occurrence: "Katı",
        stateofmatter: "Radyoaktif",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Amerikyum",
        atomicnumber: 95,
        symbol: "Am",
        category: "Aktinit",
        atomicweight: "[243]",
        atomicweightfull: "-",
        occurrence: "Katı",
        stateofmatter: "Sentetik",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Küriyum",
        atomicnumber: 96,
        symbol: "Cm",
        category: "Aktinit",
        atomicweight: "[247]",
        atomicweightfull: "-",
        occurrence: "Katı",
        stateofmatter: "Sentetik",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Berkelyum",
        atomicnumber: 97,
        symbol: "Bk",
        category: "Aktinit",
        atomicweight: "[247]",
        atomicweightfull: "-",
        occurrence: "Katı",
        stateofmatter: "Sentetik",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Kaliforniyum",
        atomicnumber: 98,
        symbol: "Cf",
        category: "Aktinit",
        atomicweight: "[251]",
        atomicweightfull: "-",
        occurrence: "Katı",
        stateofmatter: "Sentetik",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Aynştaynyum",
        atomicnumber: 99,
        symbol: "Es",
        category: "Aktinit",
        atomicweight: "[252]",
        atomicweightfull: "-",
        occurrence: "Katı",
        stateofmatter: "Sentetik",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Fermiyum",
        atomicnumber: 100,
        symbol: "Fm",
        category: "Aktinit",
        atomicweight: "[257]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Mendelevyum",
        atomicnumber: 101,
        symbol: "Md",
        category: "Aktinit",
        atomicweight: "[258]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Nobelyum",
        atomicnumber: 102,
        symbol: "Yok",
        category: "Aktinit",
        atomicweight: "[259]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Lavrensiyum",
        atomicnumber: 103,
        symbol: "Lr",
        category: "Aktinit",
        atomicweight: "[266]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 0,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 3,
        visible: true
    },
    {
        name: "Rutherfordiyum",
        atomicnumber: 104,
        symbol: "Rf",
        category: "Geçiş metali",
        atomicweight: "[267]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 4,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Dubniyum",
        atomicnumber: 105,
        symbol: "Db",
        category: "Geçiş metali",
        atomicweight: "[268]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 5,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Seaborgiyum",
        atomicnumber: 106,
        symbol: "Sg",
        category: "Geçiş metali",
        atomicweight: "[269]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 6,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Bohriyum",
        atomicnumber: 107,
        symbol: "Bh",
        category: "Geçiş metali",
        atomicweight: "[270]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 7,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Hassiyum",
        atomicnumber: 108,
        symbol: "Hs",
        category: "Geçiş metali",
        atomicweight: "[269]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 8,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Meitneryum",
        atomicnumber: 109,
        symbol: "Mt",
        category: "Bilinmiyor",
        atomicweight: "[278]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 9,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Darmstadtiyum",
        atomicnumber: 110,
        symbol: "Ds",
        category: "Bilinmiyor",
        atomicweight: "[281]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 10,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Röntgenyum",
        atomicnumber: 111,
        symbol: "Rg",
        category: "Bilinmiyor",
        atomicweight: "[282]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 11,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Kopernikum",
        atomicnumber: 112,
        symbol: "Cn",
        category: "Zayıf metal",
        atomicweight: "[285]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 12,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Nihonyum",
        atomicnumber: 113,
        symbol: "Nh",
        category: "Bilinmiyor",
        atomicweight: "[286]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 13,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Flerovyum",
        atomicnumber: 114,
        symbol: "Fl",
        category: "Bilinmiyor",
        atomicweight: "[289]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 14,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Moskoviyum",
        atomicnumber: 115,
        symbol: "Mc",
        category: "Bilinmiyor",
        atomicweight: "[290]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 15,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Livermoryum",
        atomicnumber: 116,
        symbol: "Lv",
        category: "Bilinmiyor",
        atomicweight: "[293]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 16,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Tennesin",
        atomicnumber: 117,
        symbol: "Ts",
        category: "Bilinmiyor",
        atomicweight: "[294]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 17,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Oganesson",
        atomicnumber: 118,
        symbol: "Og",
        category: "Bilinmiyor",
        atomicweight: "[294]",
        atomicweightfull: "-",
        occurrence: "Bilinmiyor",
        stateofmatter: "Sentetik",
        group: 18,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 18,
        visible: true
    },
]
